### PR TITLE
Restore functionality of the POST test that appeared to be broken in …

### PR DESCRIPTION
**Pull request by peanutsandwich**
…the post TTU merge

During the post TTU merge, the assertion series 6.1.8.1-6.1.8.3 was partially updated to test POST/PATCH/DELETE against the session collection instead of accounts collection.

However this suffered a few problems that caused the test series to fail:
1.  The user being used to create a session isn't created by the conformance tool so it is not guaranteed to be present for all services
2. Comments, logs and variable names still referred to 'accounts' instead of 'sessions'
3. Only Assertion_6_1_8_1 was updated to use the SessionService, but the remaining assertions in the series were still using the AccountService
4. The verifyCreatedObject function fails due to the object retrieved from the service containing odata fields that the object used for creation doesn't contain

I have addressed these issues with the following changes:

1. Reverted Assertion_6_1_8_1 to use the Account Service (not clear why it was changed in the first place, so this may not be a desirable change)
2. Addressed by 1
3. Addressed by 1 (plus username change in 6_1_8_3)
4. Skip odata keys in object comparison

### CODE REVIEW

**Comment by billdodd** [comment]
I suspect that 6.1.8.1 was changed to use SessionService instead of AccountService because some systems (notably some IPMI systems) have a fixed set of account slots and do not support adding and deleting them using POST and DELETE.

Wondering if a better approach to solving (1) is to require specifying an existing test account in the config (properties.json).

**Comment by mraineri** [comment]
Assigning to self to review further

**Comment by mraineri** [comment]
@peanutsandwich while members of the Account Collection will typically be deleteable, it's actually not necessary. There are shipping implementations that have a static user account list, and the client can change user names, change passwords, lock unused accounts by PATCHing the Account resource. While this isn't really the Redfish way of doing things, it is technically valid. Is there a real need to change the target collection from the Session Collection to Account Collection?

**Comment by peanutsandwich** [comment]
This PR wasn’t really intended to move from the Session Collecion to the Account Collection, but rather to fix the steps so that they were consistent. I implemented it as a move back to the Account Collection purely because that involved the least change (the majority of the steps in the group were still referring to the Account Collection).

If the decision is to go to the Session Collection then it can be reworked to do that.

**Comment by mraineri** [comment]
Thanks for clarifying. We still think the most reliable collection to test is the Session Collection for this requirement.

**Comment by PhillipWatts1012** [comment]
the test works fine using SessionService, but the user and password used must be valid.
If we continue to use SessionService and post to Sessions using the same user/password that is in properties.json it works fine.   
so we recommend staying with SessionService but using the user/passwd from properties.json.
No reason to add a new user.

**Comment by mraineri** [comment]
2/15: Closing; this has been addressed via an alternate mechanism from PR #73

**Pull request closed without merging**
