### PR TITLE
Merge from TTU updates

### PR DESCRIPTION
**Pull request by ghazanfarttu**

### CODE REVIEW

**Comment by mraineri** [comment]
Few things we need to adjust at first glance:
- Need to update the licensing for BSD-3
- Need to remove .pyc and the Visual Studio files
- Need to scrub for other files that should be pulled

**Comment by billdodd** [comment]
In commit d87d88b I fixed many runtime errors that were causing the tool to terminiate early. With these fixes I was able to do a complete run against an Intel system. I'm still in the process of trying to get complete runs on a Dell and an HPE system, so expect to have some more fixes in a subsequent commit.

**Comment by billdodd** [comment]
With my fixes in commit d87d88b, I was also able to do a complete run against our HPE Proliant iLO system.

**Comment by billdodd** [comment]
With commit 08d90fd, I was able to do a complete run against our Dell R640 system.

**Comment by pwvancil** [comment]
approved 8/24/17   -- no running on all test systems w/o crashes

**Pull request merged**
